-- Add migration script here
CREATE TYPE session_typ AS ENUM('Active', 'Inactive');
CREATE TYPE login_stat AS ENUM('Success', 'Failed', 'Hold');

CREATE TABLE tbl_acc_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  admin_id BIGINT NOT NULL,
  session_token VARCHAR(255) NOT NULL,
  refresh_token VARCHAR(255) NOT NULL,
  is_active session_typ DEFAULT 'Active',
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '1 day'),
  cid BIGINT,
	ctime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	mid BIGINT,
	mtime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY(id)
);

CREATE TABLE tbl_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  level SMALLINT NOT NULL default 0,
  admin_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
	cid BIGINT,
	ctime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	mid BIGINT,
	mtime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY(id)
);

CREATE TABLE tbl_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  -- e.g. VIEWER/MANAGES USERS(update, remove, insert, select 'only for users')/MANAGES BOOKS(update, remove, insert, select 'only for books')/(add for more).
  role VARCHAR(255) NOT NULL DEFAULT 'VIEWER', -- we'll add a default value for a VIEWER only
  level INT NOT NULL DEFAULT 0, -- 0 means VIEWER
  cid BIGINT,
	ctime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	mid BIGINT,
	mtime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY(id)
);

CREATE TABLE tbl_acc_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  acc_id BIGINT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  log_stat login_stat NOT NULL DEFAULT 'Hold',

  cid BIGINT,
	ctime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	mid BIGINT,
	mtime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY(id)
);

ALTER TABLE tbl_acc_session
ADD FOREIGN KEY(admin_id) REFERENCES tbl_admin(id)
ON DELETE CASCADE;

ALTER TABLE tbl_acc_logs
ADD FOREIGN KEY(acc_id) REFERENCES tbl_admin(id)
ON DELETE CASCADE;

ALTER TABLE tbl_permissions
ADD FOREIGN KEY(admin_id) REFERENCES tbl_admin(id)
ON DELETE CASCADE,
ADD FOREIGN KEY(role_id) REFERENCES tbl_roles(id)
ON DELETE CASCADE;

